#!/usr/bin/env python3
"""Process README template with MyST include directives."""

import re
import sys
from pathlib import Path


def process_include_directive(match):
    """Process a single include directive."""
    include_path = match.group(1).strip()

    # Convert to absolute path
    file_path = Path(include_path)

    if not file_path.exists():
        print(f"Warning: Include file not found: {include_path}")
        return f"<!-- File not found: {include_path} -->"

    try:
        with open(file_path, encoding="utf-8") as f:
            content = f.read().rstrip()
        return content
    except Exception as e:
        print(f"Error reading {include_path}: {e}")
        return f"<!-- Error reading file: {include_path} -->"


def process_readme():
    """Process README template and generate final README.md."""
    template_file = Path("docs/README.template.md")
    output_file = Path("README.md")

    # Use existing README.md as template if no template exists
    if not template_file.exists():
        template_file = output_file

    try:
        with open(template_file, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Template file {template_file} not found!")
        sys.exit(1)

    # Pattern to match MyST include directives
    include_pattern = r"```\{include\}\s+([^`]+)\s*```"

    # Process all include directives
    processed_content = re.sub(include_pattern, process_include_directive, content)

    # Add header comment to indicate this is auto-generated
    header = """<!-- This file is auto-generated from README.template.md by .github/workflows/docs.yml -->
<!-- Do not edit this file directly - edit README.template.md instead -->

"""

    # Write the processed content
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header + processed_content)

    print(f"Successfully processed {template_file} -> {output_file}")


if __name__ == "__main__":
    process_readme()
